**Write a program to implement the Linear Regression for a sample training 
data se  stored as a .CSV file. Compute Mean Square Error by considering fe 
test data se**ts

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('revenue_prediction.csv')
df

,Id,Name,Franchise,Category,City,No_Of_Item,Order_Placed,Revenue
0,101,HungryHowie'sPizza,Yes,Mexican,Bengaluru,55,5.5,5953753
1,102,CharleysPhillySteaks,No,Varied Menu,Gurugram,72,6.8,7223131
2,103,Chuy's,Yes,Chicken,Pune,25,1.9,2555379
3,104,O'Charley's,Yes,Italian/Pizza,Mumbai,18,2.5,2175511
4,105,PolloTropical,Yes,Pizza,Noida,48,4.2,4816715
...,...,...,...,...,...,...,...,...
95,196,Wetzel'sPretzels,No,Italian/Pizza,Bengaluru,19,1.1,1270499
96,197,LaMadeleineCountryFrenchCafe,Yes,Varied Menu,Bengaluru,75,6.3,6412623
97,198,Giordano's,Yes,Varied Menu,Gurugram,77,6.2,6694797
98,199,IslandsFineBurgers&Drinks,Yes,Sports Bar,Pune,25,2.1,2344689
99,200,Mimi'sBistro&Bakery,No,BBQ,Mumbai,50,4.4,4567678

In [7]:
# Id and name of the place are not important to predict revenue, so we are going to remove them 
# df = df.drop('Id',axis=1)
df.drop('Id',axis=1,inplace=True)  #It will update the changes in actual df.

In [11]:
df.drop(columns=['Id','Name'],axis=1,inplace=True)

In [12]:
df

   Franchise       Category       City  No_Of_Item  Order_Placed  Revenue
0        Yes        Mexican  Bengaluru          55           5.5  5953753
1         No    Varied Menu   Gurugram          72           6.8  7223131
2        Yes        Chicken       Pune          25           1.9  2555379
3        Yes  Italian/Pizza     Mumbai          18           2.5  2175511
4        Yes          Pizza      Noida          48           4.2  4816715
..       ...            ...        ...         ...           ...      ...
95        No  Italian/Pizza  Bengaluru          19           1.1  1270499
96       Yes    Varied Menu  Bengaluru          75           6.3  6412623
97       Yes    Varied Menu   Gurugram          77           6.2  6694797
98       Yes     Sports Bar       Pune          25           2.1  2344689
99        No            BBQ     Mumbai          50           4.4  4567678

[100 rows x 6 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Franchise     100 non-null    object
 1   Category      100 non-null    object
 2   City          100 non-null    object
 3   No_Of_Item    100 non-null    int64
 4   Order_Placed  100 non-null    float64
 5   Revenue       100 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 4.8+ KB

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
df['City'].unique()

array(['Bengaluru', 'Gurugram', 'Pune', 'Mumbai', 'Noida'], dtype=object)

In [17]:
le = LabelEncoder()

df['City'] = le.fit_transform(df['City'])

In [20]:
for x in df:
    if(x=='City'):
        break
    df[x] = le.fit_transform(df[x])

In [21]:
df

    Franchise  Category  City  No_Of_Item  Order_Placed  Revenue
0           1        12     0          55           5.5  5953753
1           0        19     1          72           6.8  7223131
2           1         5     4          25           1.9  2555379
3           1        11     2          18           2.5  2175511
4           1        13     3          48           4.2  4816715
..        ...       ...   ...         ...           ...      ...
95          0        11     0          19           1.1  1270499
96          1        19     0          75           6.3  6412623
97          1        19     1          77           6.2  6694797
98          1        17     4          25           2.1  2344689
99          0         2     2          50           4.4  4567678

[100 rows x 6 columns]

In [59]:
X = df.iloc[:,3:-1]
X

    No_Of_Item  Order_Placed
0           55           5.5
1           72           6.8
2           25           1.9
3           18           2.5
4           48           4.2
..         ...           ...
95          19           1.1
96          75           6.3
97          77           6.2
98          25           2.1
99          50           4.4

[100 rows x 2 columns]

In [60]:
y = df['Revenue']
y

0     5953753
1     7223131
2     2555379
3     2175511
4     4816715
       ...
95    1270499
96    6412623
97    6694797
98    2344689
99    4567678
Name: Revenue, Length: 100, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=0)
x_train

    No_Of_Item  Order_Placed
43          33           2.6
62          57           5.1
3           18           2.5
71          49           4.0
45          45           3.6
..         ...           ...
96          75           6.3
67          40           3.8
64          32           2.4
47          85           7.7
44          48           4.0

[80 rows x 2 columns]

In [83]:
x_test.shape

(20, 2)

In [84]:
y_train.shape

(80,)

In [85]:
y_test.shape

(20,)

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
model = LinearRegression()
model.fit(x_train,y_train)  #Passing training data to the model

LinearRegression()

In [88]:
y_pred = model.predict(x_test)

In [89]:
y_pred

array([ 2226451.23073678,  3225433.11220471,  2033113.87118849,
        6979797.22434376, 13468446.65414698,  3343415.27639116,
       11018784.86185082,  3236198.14011354,  4643384.79649572,
        1195174.26554235,  5594140.62377926,  6716703.75479341,
        3655167.94293662,  4869017.2397705 ,  4482342.52067393,
        3053625.80847409,  3961321.5241223 ,  8902405.79191779,
        2328502.42446534,  4938773.34977256])

In [90]:
from sklearn.metrics import *

In [91]:
r2_score(y_test,y_pred)

0.770820285218

In [96]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
rmse

2147765.4974064194

In [97]:
mean_squared_error(y_test,y_pred)

4612896631849.443