## **Create a data frame with columns at least 5 observations**

1. ***Retrieve a particular column from the DataFrame***
2. ***Summarize the data frame and observe the statistics of the DataFrame 
create*** 
3. ***Observe the mean and standard deviation of the data frame and print the 
values***.d

In [1]:
import pandas as pd

In [34]:
di = {
    'Gender' : ['F','M','F','M','F','M'],
    'Age' : [28,32,26,40,35,55],
    'Salary':[45000,60000,28000,80000,95000,70000],
    'City':['Pune','Delhi','Pune','Jaipur','Pune','Jaipur']
}

In [35]:
df = pd.DataFrame(di)
df

  Gender  Age  Salary    City
0      F   28   45000    Pune
1      M   32   60000   Delhi
2      F   26   28000    Pune
3      M   40   80000  Jaipur
4      F   35   95000    Pune
5      M   55   70000  Jaipur

In [36]:
#Retrieve a particular column from the DataFrame
df['Salary']

0    45000
1    60000
2    28000
3    80000
4    95000
5    70000
Name: Salary, dtype: int64

In [37]:
df.loc[[2,4],['Gender','Salary']]

  Gender  Salary
2      F   28000
4      F   95000

In [38]:
df.iloc[3:6,2:4]  # i -> indexing in iloc.

   Salary    City
3   80000  Jaipur
4   95000    Pune
5   70000  Jaipur

In [47]:
#Summarize the data frame and observe the statistics of the DataFrame created 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  6 non-null      object
 1   Age     6 non-null      int64
 2   Salary  6 non-null      int64
 3   City    6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [48]:
df.describe()  #It gives us the statistical info about our dataset.

            Age        Salary
count   6.00000      6.000000
mean   36.00000  63000.000000
std    10.56409  24166.091947
min    26.00000  28000.000000
25%    29.00000  48750.000000
50%    33.50000  65000.000000
75%    38.75000  77500.000000
max    55.00000  95000.000000

In [49]:
df.describe(include='O')  #It includes object data type column.

       Gender  City
count       6     6
unique      2     3
top         F  Pune
freq        3     3

In [50]:
df.describe(include='all')

       Gender       Age        Salary  City
count       6   6.00000      6.000000     6
unique      2       NaN           NaN     3
top         F       NaN           NaN  Pune
freq        3       NaN           NaN     3
mean      NaN  36.00000  63000.000000   NaN
std       NaN  10.56409  24166.091947   NaN
min       NaN  26.00000  28000.000000   NaN
25%       NaN  29.00000  48750.000000   NaN
50%       NaN  33.50000  65000.000000   NaN
75%       NaN  38.75000  77500.000000   NaN
max       NaN  55.00000  95000.000000   NaN

In [51]:
df['City'].value_counts()  #Returns the frequency of unique values.

City
Pune      3
Jaipur    2
Delhi     1
Name: count, dtype: int64

In [52]:
df['Gender'].unique() #Return all the unique values present in a column.

array(['F', 'M'], dtype=object)

In [53]:
df['City'].nunique()  # -> REturns the number of unique values present in a column.

3